### PR TITLE
Fixing Sample data download on Fedora

### LINKED ISSUE #1203: no browser shown when attempting download
**Describe the bug**
Linux (fedora 32), 1.8.0 A3.

> Going to Help => Sample Data => _any  selection_

results in nothing -- no browser window or tab is opened, no error message.

When attempting the download, bot Chrome & Firefox were open, both are able to connect to ftp://nitrc

```
[bergman@huajiao 1.8.0.Alpha3]$ xdg-settings get  default-url-scheme-handler
[bergman@huajiao 1.8.0.Alpha3]$ xdg-settings get  default-web-browser
firefox.desktop
```

### LINKED ISSUE #1226: CaPTk libraries within AppImage take precedence over same library in host system, problem if versions conflict
**Describe the bug**
CaPTk provided libraries (Qt) take precedence over system libraries. This is a problem when an operation that executes outside of CaPTk uses a library that exists within CaPTk but requires a higher version.

Specifically, the process for sample data downloads uses the system URL handler. Under Fedora 32  the URL handler in the KDE environment is `kde-open5`, which requires Qt 5.13. The consequence is that sample data cannot be downloaded.

Currently, this is known to affect Fedora 32 now, but it will certainly arise in other environments during the lifespan of CaPTk 1.8.0.

**To Reproduce**
1. Install Fedora 32
2. Install KDE
3. Use KDE
4. Run CaPTk
5. Go to Help => Sample Data => _application_

```
[bergman@huajiao .mount_captkansUtI]$ kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by kde-open5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5KIOWidgets.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5KIOCore.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5I18n.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5CoreAddons.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5KIOGui.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5JobWidgets.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5Service.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5Completion.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5IconThemes.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5ConfigWidgets.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5WidgetsAddons.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5ConfigGui.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5ConfigCore.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.14' not found (required by /lib64/libQt5Xml.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.14.2_PRIVATE_API' not found (required by /lib64/libQt5Xml.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5Crash.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5DBusAddons.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5AuthCore.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5WindowSystem.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.14' not found (required by /lib64/libQt5X11Extras.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Widgets.so.5: version `Qt_5.14.2_PRIVATE_API' not found (required by /lib64/libQt5Svg.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Gui.so.5: version `Qt_5.14.2_PRIVATE_API' not found (required by /lib64/libQt5Svg.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.14' not found (required by /lib64/libQt5Svg.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.14.2_PRIVATE_API' not found (required by /lib64/libQt5Svg.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5Archive.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5ItemViews.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5Codecs.so.5)
kde-open5: /tmp/.mount_captkansUtI/usr/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /lib64/libKF5GuiAddons.so.5)

[bergman@huajiao .mount_captkansUtI]$ find /usr/lib* -iname "*libQt5Core.so*"
/usr/lib64/libQt5Core.so.5
/usr/lib64/libQt5Core.so
/usr/lib64/libQt5Core.so.5.14.2
/usr/lib64/libQt5Core.so.5.14
find: ‘/usr/libexec/initscripts/legacy-actions/auditd’: Permission denied
[bergman@huajiao .mount_captkansUtI]$ rpm -qf /usr/lib64/libQt5Core.so.5
qt5-qtbase-5.14.2-5.fc32.x86_64
[bergman@huajiao .mount_captkansUtI]$ 
[bergman@huajiao .mount_captkansUtI]$ 
```

### LINKED ISSUE #1276: Sample data downloads should show progress
Sample data downloads should show progress

### PR DESCRIPTION
**Pull request by ashishsingh18**
Fix #1226
Fix #1203
Fix #1276 

-Uses Qt network download mechanism
-Does sequential downloads via queuing mechanism
-Shows download progress
-Shows download speed
-Sample data/model downloads go through the same mechanism
-Downloads also get logged
-To be migrated to CaPTk2

### CODE REVIEW

**Comment by ashishsingh18** [comment]
@CBICA/devteam Can we please test the sample data download on various platforms? 
https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2229&view=artifacts&type=publishedArtifacts

**Comment by sarthakpati** [comment]
Does not work on Windows 10. 

- Installation successful
- Help > Sample Data > LIBRA
- Asks where I want to save the zip file
- I select Downloads
- Nothing else happens (I don't see any related processes running, either)

**Comment by ashishsingh18** [comment]
> 
> 
> > https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2229&view=artifacts&type=publishedArtifacts
> 
> Does not work on Windows 10.
> 
>     * Installation successful
> 
>     * Help > Sample Data > LIBRA
> 
>     * Asks where I want to save the zip file
> 
>     * I select Downloads
> 
>     * Nothing else happens (I don't see any related processes running, either)

Can you check the location you gave for save? There is no progress but it downloads.

**Comment by sarthakpati** [comment]
> > https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2229&view=artifacts&type=publishedArtifacts
> 
> Does not work on Windows 10.
> 
> * Installation successful
> * Help > Sample Data > LIBRA
> * Asks where I want to save the zip file
> * I select Downloads
> * Nothing else happens (I don't see any related processes running, either)

My mistake: sample data downloaded, but instead of LIBRA it download EGFRvIII, for some reason. Also, since there is no feedback to the user (progress bar update would be nice), I had no idea if it was doing anything.

**Comment by ashishsingh18** [comment]
> 
> 
> > > https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2229&view=artifacts&type=publishedArtifacts
> > 
> > 
> > Does not work on Windows 10.
> > 
> > * Installation successful
> > * Help > Sample Data > LIBRA
> > * Asks where I want to save the zip file
> > * I select Downloads
> > * Nothing else happens (I don't see any related processes running, either)
> 
> My mistake: sample data downloaded, but instead of LIBRA it download EGFRvIII, for some reason. Also, since there is no feedback to the user (progress bar update would be nice), I had no idea if it was doing anything.

It is weird that it downloaded EGFRvIII. It should have downloaded LIBRA. I am not changing the link and this is plugged in to `fMainWindow::help_Download(..)` method. Perhaps this is another bug that was always there.  I agree, we will need to add progress, I wanted to make sure that the download itself is working before extending the code for progress.

**Comment by MarkBergman-cbica** [comment]
Fedora 32:

	Help => Sample Data => *
		correctly allows the choice of a download directory

	
No progress bar shown for any download.

qt.network.ssl errors shown on first download attempt (not repeated for each), details below

Individual download status, order of actions:
	EGFR SVMindex			no download, no error (first download attempt)
	EGFR  Surrogate index		no download, no error (first download attempt)
	LIBRA				Successful
	EGFR  Surrogate index		second download attempt, CaPTk crashed w. segfault during the same session, possibly due to download in progress, traceback below

{Restarted CaPTk}
	EGFR SVMindex			successful
		expanded zip file, then removed zip file & extracted contents
	EGFR SVMindex			second download attempt, CaPTk crashed w. segfault during the same session

{Restarted CaPTk}
	SurvivalPredictor		no download
	MolecularSubtype		CaPTk crashed w. segfault during the same session, possibly due to download in progress

{Restarted CaPTk}
	EGFR SVMindex			successful
		waited until download was complete
	EGFR  Surrogate index		segfault immediately on download attempt



It appears as if a lot of buffering takes place (ie., the partially downloaded file on-disk doesn't start at "1" byte, but
at several MB(?)). 

The "2nd" download attempt, whether serial or simultaneous, the same dataset or different, consistently causes a segfault.





----------------------- qt.network.ssl ---------------
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL


----------------------- traceback --------------------
Received signal 11 SEGV_MAPERR 000000000040
#0 0x7f24d5b1fa4f <unknown>
#1 0x7f24d5b1fe4b <unknown>
#2 0x7f24d5b204ce <unknown>
#3 0x7f24d192fa90 <unknown>
#4 0x7f24d1ae5d40 QString::operator=()
#5 0x0000009acc52 <unknown>
#6 0x000000f9c3ef <unknown>
#7 0x7f24d1c5c8a9 QMetaObject::activate()
#8 0x7f24d2c3c532 QMenu::triggered()
#9 0x7f24d2c3f621 QMenuPrivate::_q_actionTriggered()
#10 0x7f24d2c48821 QMenu::qt_static_metacall()
#11 0x7f24d1c5c8a9 QMetaObject::activate()
#12 0x7f24d2ad2b62 QAction::triggered()
#13 0x7f24d2ad4f80 QAction::activate()
#14 0x7f24d2c3dcba QMenuPrivate::activateCausedStack()
#15 0x7f24d2c44dc6 QMenuPrivate::activateAction()
#16 0x7f24d2c45df9 QMenu::mouseReleaseEvent()
#17 0x7f24d2b16828 QWidget::event()
#18 0x7f24d2c4830b QMenu::event()
#19 0x7f24d2ad8b3c QApplicationPrivate::notify_helper()
#20 0x7f24d2ae030f QApplication::notify()
#21 0x7f24d1c30e28 QCoreApplication::notifyInternal2()
#22 0x7f24d2adf24a QApplicationPrivate::sendMouseEvent()
#23 0x7f24d2b30730 QWidgetWindow::handleMouseEvent()
#24 0x7f24d2b32eeb QWidgetWindow::event()
#25 0x7f24d2ad8b3c QApplicationPrivate::notify_helper()
#26 0x7f24d2adfd30 QApplication::notify()
#27 0x7f24d1c30e28 QCoreApplication::notifyInternal2()
#28 0x7f24d229c767 QGuiApplicationPrivate::processMouseEvent()
#29 0x7f24d229dd15 QGuiApplicationPrivate::processWindowSystemEvent()
#30 0x7f24d22799fb QWindowSystemInterface::sendWindowSystemEvents()
#31 0x7f24bcb9d81a xcbSourceDispatch()
#32 0x7f24caf5878f g_main_context_dispatch
#33 0x7f24caf58b18 <unknown>
#34 0x7f24caf58be3 g_main_context_iteration
#35 0x7f24d1c881ef QEventDispatcherGlib::processEvents()
#36 0x7f24d1c2f78a QEventLoop::exec()
#37 0x7f24d1c38190 QCoreApplication::exec()
#38 0x000000443aea <unknown>
#39 0x7f24d0db1042 __libc_start_main
#40 0x00000047e299 <unknown>
  r8: 0000000007fd46f0  r9: 0000000000000005 r10: 0000000000000003 r11: 0000000005d171c0
 r12: 00007fff30323d20 r13: 00007fff30326900 r14: 00007fff30323cc0 r15: 00007fff30323d40
  di: 0000000005facd40  si: 00007fff30323d60  bp: 00007fff30323d60  bx: 0000000005facd40
  dx: 0000000006b6cb10  ax: 0000000000000040  cx: 00007f24d0f4da00  sp: 00007fff30323c40
  ip: 00007f24d1ae5d40 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000040
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by AlexanderGetka-cbica** [comment]
Windows 10:
When I attempt to download LIBRA sample data, I get LIBRA sample data, not the EGFRvIII stuff. I also get the crash mentioned by mark if I initiate another download after the first.

**Comment by ashishsingh18** [comment]
Thank you all for testing this out. 

So there's no progress shown because I haven't implemented it. I wanted to test the download functionality first particularly on Fedora. Thanks @MarkBergman-cbica for reporting the other issues on Fedora.  I know why it fails on 2nd attempt and I can reproduce it on Windows as well. It was my mistake - deleting the object.

@MarkBergman-cbica could you please send me the exact error you see about ssl? Not sure how we will replicate and fix this on our side though without a Fedora system.
`qt.network.ssl errors shown on first download attempt (not repeated for each), details below`

I am not sure about buffering as this could be internal to Qt, but will take a look. I guess it shouldn't matter as long the progress is shown and the download completes successfully.

I am also not sure why the download didn't happen the first time around for the below cases. @MarkBergman-cbica could you please re-test this? Just click on any one of these once.
```
Individual download status, order of actions:
	EGFR SVMindex			no download, no error (first download attempt)
	EGFR  Surrogate index		no download, no error (first download attempt)
```

Questions:
1) Do we need a 'File Save' dialog? Or can we directly save to 'Download' folder? This might help with the issue that @sarthakpati mentioned about data/filename mismatch.
2) Did the 'File Save' dialog open the 'Download' folder by default on each of the platforms we tested?

**Comment by AlexanderGetka-cbica** [comment]
Re: (2), It opened my user Downloads folder on Windows, yes. I'll give this a shot on my Ubuntu workstation as well.

**Comment by sarthakpati** [comment]
1. I think asking the user for the location is the right way to go.
2. The default can be the user's home directory, I'd guess.

**Comment by ashishsingh18** [comment]
@CBICA/devteam Can we re-test this? 
https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2250&view=artifacts&type=publishedArtifacts

**Comment by sarthakpati** [comment]
> @CBICA/devteam Can we re-test this?
> https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2250&view=artifacts&type=publishedArtifacts

- Default save location is to Downloads, which is great!
- Progress bar is working (yay!):
image
- Allows me to select download of another file which begins **AFTER** the previous one is done (woo hoo!)

**Comment by AlexanderGetka-cbica** [comment]
Seems to work great on Linux as well, with one exception:

Selecting "Perfusion Alignment" crashes CaPTk instantly even before the file dialog pops up. I am able to reproduce this on Windows. Opening another issue for this.

**Comment by ashishsingh18** [comment]
> 
> 
> Seems to work great on Linux as well, with one exception:
> 
> Selecting "Perfusion Alignment" crashes CaPTk instantly even before the file dialog pops up. I am able to reproduce this on Windows. Opening another issue for this.

Thats because PerfusionAlignment entry isn't available in the yaml

**Comment by ashishsingh18** [comment]
It works on macOS as well.

**Comment by ashishsingh18** [comment]
@MarkBergman-cbica Could you please test on Fedora? https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2253&view=artifacts&type=publishedArtifacts

File: src/view/gui/fMainWindow.cpp [hunk 1]
```diff
@@ -9662,7 +9689,7 @@ void fMainWindow::closeEvent(QCloseEvent* event)
   }
 }
 
-void fMainWindow::updateProgress(int progress, std::string message, int max)
+void fMainWindow::updateProgress(qint64 progress, std::string message, qint64 max)
```
Comment (AlexanderGetka-cbica) [inline src/view/gui/fMainWindow.cpp:9692]: Will this break other applications that connect to the updateProgress slot? Or does it automatically cast?

Comment (ashishsingh18) [reply src/view/gui/fMainWindow.cpp:9692]: I guess it should auto cast, but we should test. There are no connect failure errors (due to mismatched signals/slots) thrown which are usually thrown at compile time.

Comment (sarthakpati) [reply src/view/gui/fMainWindow.cpp:9692]: Good catch. @ashishsingh18: There is actually no reason to use special data types unless absolutely needed, right?

Comment (sarthakpati) [reply src/view/gui/fMainWindow.cpp:9692]: From [Qt doc](https://doc.qt.io/qt-5/qtglobal.html#qint64-typedef):

```
typedef qint64
Typedef for long long int (__int64 on Windows). This type is guaranteed to be 64-bit on all platforms supported by Qt.
```

Shouldn't create any issue, just that there is no reason to use it...

Comment (ashishsingh18) [reply src/view/gui/fMainWindow.cpp:9692]: I don't think I understood the 'no reason to use it' part.
The progress we are getting from Qt Network class is in qint64 and that is getting propagated to our GUI. We can replace qint64 with long long in our code for easy reading. But I don't think typedef is a problem. I guess @AlexanderGetka-cbica's quesion was - since there is a mismatch between qint64( long long int) and int( which is what our older UpdateProgress slot was using), will this be a problem with other signals that connect to the same slot. Or would we need to update all of them?

Comment (sarthakpati) [reply src/view/gui/fMainWindow.cpp:9692]: I guess this is a stylistic thing but I prefer not to use "custom" data-types. 🤷 

As far as @AlexanderGetka-cbica's question goes, the casting from `int` to `long long` shouldn't be an issue for other applications.

**Comment by ashishsingh18** [comment]
Downloads are failing on Fedora. See below message from @MarkBergman-cbica 

Fails.

Each download attempt (5 different datasets attempted) shows an immediate "Download Finished!" message next to the empty progress bar, and errors on the command-line used to launch the GUI:

-------------------
[bergman@huajiao Downloads]$  fname:  "/datil/home/bergman/Downloads/CaPTk/EGFRvIIISVMIndex.zip"
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL Downloading ftp://www.nitrc.org/home/groups/captk/downloads/SampleData_1.6.0/EGFRvIIISVMIndex.zip...
msg = "Downloading: EGFRvIIISVMIndex.zip at 0.0 bytes/sec"
Failed: Logging in to www.nitrc.org failed: authentication required
0/1 files downloaded successfully

**Comment by ashishsingh18** [comment]
I guess it was failing earlier due to NITRC issues. The download may now complete, though the ssl errors may still pop up.

Some relevant posts on ssl errors that were fixed with installation of `libssl1.0-dev`
https://stackoverflow.com/questions/52210603/qt-and-openssl-incompatible-version-on-ubuntu

**Comment by sarthakpati** [comment]
The error posted by @MarkBergman-cbica was probably due to the NITRC server issues and should be resolved, now.

**Comment by MarkBergman-cbica** [comment]
In the message dated: Mon, 31 Aug 2020 18:04:42 -0000,
The pithy ruminations from Ashish Singh on 
[[External] Re: [CBICA/CaPTk] Fixing Sample data download on Fedora (#1275)] were:
=> I guess it was failing earlier due to NITRC issues. The download may now complete, though the ssl errors may still pop up.

Yes.

Downloads now work -- fast and the interface is fine.

The progress bar works.

Queuing downloads (ie., beginning download N+1 while download N is in progress) works.

There are SSL messages on the console:

	qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
	qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
	qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
	qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
	qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
	qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
	qt.network.ssl: QSslSocket: cannot resolve sk_new_null
	qt.network.ssl: QSslSocket: cannot resolve sk_push
	qt.network.ssl: QSslSocket: cannot resolve sk_free
	qt.network.ssl: QSslSocket: cannot resolve sk_num
	qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
	qt.network.ssl: QSslSocket: cannot resolve sk_value
	qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
	qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
	qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
	qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
	qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
	qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
	qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
	qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
	qt.network.ssl: QSslSocket: cannot resolve SSLeay
	qt.network.ssl: Incompatible version of OpenSSL

There are also many console messages that correspond to the progress bar:

	msg = "Downloading: SurvivalPredictor.zip at 2.9 kB/s"
	msg = "Downloading: SurvivalPredictor.zip at 37.7 kB/s"
several hundred for some datasets...

Are those just for debugging? Can they be surpressed for the release?

Mark

=> 
=> Some relevant posts on ssl errors that were fixed with installation of `libssl1.0-dev`
=> https://stackoverflow.com/questions/52210603/qt-and-openssl-incompatible-version-on-ubuntu 
=> 
=> -- 
=> You are receiving this because you were mentioned.
=> Reply to this email directly or view it on GitHub:
=> https://github.com/CBICA/CaPTk/pull/1275#issuecomment-683938495

-- 
Mark Bergman                                           voice: 215-746-4061       
mark.bergman@pennmedicine.upenn.edu                      fax: 215-614-0266
http://www.med.upenn.edu/cbica/
IT Technical Director, Center for Biomedical Image Computing and Analytics
Department of Radiology                         University of Pennsylvania

**Comment by ashishsingh18** [comment]
Thanks @MarkBergman-cbica for re-testing and good to know that the downloads are indeed working.

Most console messages were for debugging. Messages like the following can be suppressed. 
`msg = "Downloading: SurvivalPredictor.zip at 2.9 kB/s"`

I am not sure if we can suppress the ssl errors though.

**Comment by ashishsingh18** [comment]
@CBICA/devteam This is ready for testing and review. 
https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2280&view=artifacts&type=publishedArtifacts

**Comment by ashishsingh18** [comment]
Windows build is failing at upload step due to lack of  enough space.
image

@CBICA/devteam

**Comment by AlexanderGetka-cbica** [comment]
What do we do about this? Do we need to clean up our space on NITRC?

**Comment by ashishsingh18** [comment]
> 
> 
> What do we do about this? Do we need to clean up our space on NITRC?

There is a new error on windows now.
image

**Comment by MarkBergman-cbica** [comment]
In the message dated: Thu, 03 Sep 2020 12:07:55 -0700,
The pithy ruminations from Ashish Singh on 
[[External] Re: [CBICA/CaPTk] Fixing Sample data download on Fedora (#1275)] were:
=> > 
=> > 
=> > What do we do about this? Do we need to clean up our space on NITRC?
=> 
=> There is a new error on windows now.
=> image

Unrelated to NITRC, and I'm looking into it.

Also, it's easier to troubleshoot with a link to the actual page
(https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2303&view=logs&j=e56f6082-d738-5dfe-6952-dd986d956652&t=183706f4-62f6-5ba8-3505-d37d64e49908&l=16)
rather than a screenshot.

-- 
Mark Bergman                                           voice: 215-746-4061       
mark.bergman@pennmedicine.upenn.edu                      fax: 215-614-0266
http://www.med.upenn.edu/cbica/
IT Technical Director, Center for Biomedical Image Computing and Analytics
Department of Radiology                         University of Pennsylvania

**Comment by sarthakpati** [comment]
I am curious if it is because sbia-pc132 is actually running out of space on the C drive [[ref](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2290&view=logs&j=c47385da-48c0-5f1b-bcdd-8c6adf12a41d&t=e66bad55-1542-46b3-9313-40abf3aef6b0)]; in the previous build, the installer did get generated [[ref](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2290&view=logs&j=c47385da-48c0-5f1b-bcdd-8c6adf12a41d&t=8b9b18e2-5c5f-5c95-7e84-1f086836c632&l=2157)], however...

**Comment by sarthakpati** [comment]
> I am curious if it is because sbia-pc132 is actually running out of space on the C drive [[ref](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2290&view=logs&j=c47385da-48c0-5f1b-bcdd-8c6adf12a41d&t=e66bad55-1542-46b3-9313-40abf3aef6b0)]; in the previous build, the installer did get generated [[ref](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2290&view=logs&j=c47385da-48c0-5f1b-bcdd-8c6adf12a41d&t=8b9b18e2-5c5f-5c95-7e84-1f086836c632&l=2157)], however...

Re-running this so that it picks up sbia-pc130 as the Windows agent (which is my desktop)... Let's see what happens.

**Comment by sarthakpati** [comment]
Latest artefacts: https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2310&view=artifacts&type=publishedArtifacts

**Comment by sarthakpati** [comment]
> Latest artifacts: https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2310&view=artifacts&type=publishedArtifacts

Working on Windows.

**Comment by ashishsingh18** [comment]
This is ready for review @CBICA/devteam

**Comment by AlexanderGetka-cbica** [comment]
Working on Ubuntu as well.

**Review by AlexanderGetka-cbica — APPROVED** [review]
Overall this looks really good and it works well in the test artifacts.

**Comment by sarthakpati** [comment]
Should we wait for @MarkBergman-cbica to test on Fedora before merging?

**Comment by ashishsingh18** [comment]
> 
> 
> Should we wait for @MarkBergman-cbica to test on Fedora before merging?

Downloads were working for @MarkBergman-cbica as per earlier tests. The only issue was the ssl messages that were shown on the console.

**Review by sarthakpati — APPROVED** [review]

**Comment by MarkBergman-cbica** [comment]
Downloads work under Fedora32 (fast, good progress bar, correct handling of multiple queued download requests).

SSL messages are still present:

```
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL
```

**Comment by ashishsingh18** [comment]
> 
> 
> Downloads work under Fedora32 (fast, good progress bar, correct handling of multiple queued download requests).
> 
> SSL messages are still present:
> 
> ```
> qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
> qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
> qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
> qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
> qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
> qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
> qt.network.ssl: QSslSocket: cannot resolve sk_new_null
> qt.network.ssl: QSslSocket: cannot resolve sk_push
> qt.network.ssl: QSslSocket: cannot resolve sk_free
> qt.network.ssl: QSslSocket: cannot resolve sk_num
> qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
> qt.network.ssl: QSslSocket: cannot resolve sk_value
> qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
> qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
> qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
> qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
> qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
> qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
> qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
> qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
> qt.network.ssl: QSslSocket: cannot resolve SSLeay
> qt.network.ssl: Incompatible version of OpenSSL
> ```

Opened a new issue regarding this #1290
