### PR TITLE
fix #880

### LINKED ISSUE #880: Improve error message in case of missing (required) files
**Describe the bug**
When required files are not present, the error message needs improvement

**To Reproduce**
```

(base) [bergmama@cubic-login2 ~]$ captk Deepmedic -t1 t1_LPS_rSRI.nii.gz -t1c t1ce_LPS_rSRI.nii.gz -t2 t2_LPS_rSRI.nii.gz -fl flair_LPS_rSRI.nii.gz -o output_dir -md deepMedic/saved_models/skullStripping
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/Remote/MGHIO/src/itkMGHImageIO.cxx:160:
itk::ERROR: MGHImageIO(0x17a78c0): A FileName must be specified.
(base) [bergmama@cubic-login2 ~]$ 
```

**Expected behavior**

(base) [bergmama@cubic-login2 ~]$ captk Deepmedic -t1 t1_LPS_rSRI.nii.gz -t1c t1ce_LPS_rSRI.nii.gz -t2 t2_LPS_rSRI.nii.gz -fl flair_LPS_rSRI.nii.gz -o output_dir -md deepMedic/saved_models/skullStripping
Error: t1 file "t1_LPS_rSRI.nii.gz" not found
```

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes issue #880

### CODE REVIEW

File: src/cbica_toolkit/src/cbicaITKSafeImageIO.h [hunk 1]
```diff
@@ -776,6 +776,12 @@ namespace cbica
   template <class TImageType = ImageTypeFloat3D >
   typename TImageType::Pointer ReadImage(const std::string &fName, const std::string &supportedExtensions = ".nii.gz,.nii,.dcm", const std::string &delimitor = ",")
   {
+    if (!cbica::exists(fName))
+    {
+      std::cerr << "The file name '" << fName << "' was't found.\n";
+      nullptr;
```
Comment (dboun) [inline src/cbica_toolkit/src/cbicaITKSafeImageIO.h]: return before nullptr?

Comment (sarthakpati) [reply src/cbica_toolkit/src/cbicaITKSafeImageIO.h]: Nice catch, resolved.
