### PR TITLE
replacing dcm2nii with dcm2niix

### LINKED ISSUE #1240: Dicom to Nifti conversion doesn't work for DTI and Perfusion
**Describe the bug**
In the dicom to conversion in Utilities, the 4th dimension is not recognized for both DTI and Perfusion and .bval and .bvec is not extracted for DTI.

**To Reproduce**

Input and output are at the below location. I also made conversion outputs using dcm2niix for comparison. The output of dcm2niix is what is expected.

```
dir="/cbica/home/sakoc/comp_space/lab/captk/180b/d2n"
for m in dti perf; do

    fin=`ls -1 $dir/dcm_$m/* | head -n 1`      # <----- getting one filename as Utilities -d2n input is one dicom, not dicom directory
    /cbica/software/lab/captk/centos7/1.8.0.Beta/bin/Utilities \
         -i $fin \
         -o $dir/out_captk/$m.nii.gz \
	 -d2n

    /cbica/home/sakoc/software/dcm2niix/v1.0.20190410/dcm2niix \
         -o out_dcm2niix -z y -f $m dcm_$m
    
done
```
output:
```
$ for i in out_*/*nii.gz; do echo $i,`Utilities -i $i -inf | grep Dimensions`,`Utilities -i $i -inf | grep Size`; done
out_captk/dti.nii.gz,Dimensions,3,Size,128x128x442
out_captk/perf.nii.gz,Dimensions,3,Size,128x128x900
out_dcm2niix/dti.nii.gz,Dimensions,4,Size,128x128x34x13   # <-- this is what is expected
out_dcm2niix/perf.nii.gz,Dimensions,4,Size,128x128x20x45  # <-- this is what is expected
```

**Expected behavior**
DTI dicoms produce a 4D nifti and 2 directional files (.bval and .bvec) files
Perfusion dicoms produce a 4D nifti file.

**CaPTk Version**
1.8.0.Beta

**Desktop (please complete the following information):**
 - OS: centos7

### LINKED ISSUE #1251: Modify backend for dicom to nifti from GUI side to dcm2niix
Modify backend for dicom to nifti from GUI side to dcm2niix

### PR DESCRIPTION
**Pull request by ashishsingh18**
Fix #1240
Fix #1251

-adds dcm2niix
-replaces dcm2nii by dcm2niix for dicom to nifti conversion via GUI
-dcm2nii still there in case we want to revert
-also produces BIDS json

### CODE REVIEW

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica is the windows build stuck?

**Comment by AlexanderGetka-cbica** [comment]
Seems like end-to-end mac build was stuck possibly due to an Azure outage. Self-hosted windows build was never queued -- seems like SBIA-PC132 is offline.

**Comment by sarthakpati** [comment]
> seems like SBIA-PC132 is offline

Perhaps @MarkBergman-cbica can do a power cycle? You should put in an RT for this.

**Comment by AlexanderGetka-cbica** [comment]
agent is running again

**Comment by ashishsingh18** [comment]
Do we need a dummy commit to re-trigger?

**Comment by AlexanderGetka-cbica** [comment]
It should re-trigger automatically. Our retained build is now trying to run -- I'll cancel that one so it can get to the latest version.

**Comment by ashishsingh18** [comment]
Can we test the created packages? https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2153&view=artifacts&type=publishedArtifacts

**Comment by ashishsingh18** [comment]
Works on Windows.

File: src/view/gui/fDCM2NIfTI.cpp [hunk 1]
```diff
@@ -30,7 +30,7 @@ fDCM2NIfTIConverter::fDCM2NIfTIConverter()
   }
 
 #elif __linux__
-  m_exe =  "." + QApplication::applicationDirPath() + "/dcm2niix";
+  m_exe =  /*"." + */QApplication::applicationDirPath() + "/dcm2niix";
```
Comment (sarthakpati) [inline src/view/gui/fDCM2NIfTI.cpp:33]: Actually, this will not work for macOS (yay for the fruit company). You need to use `getApplicationPath("dcm2niix")` to get it working across platforms.

Comment (ashishsingh18) [reply src/view/gui/fDCM2NIfTI.cpp:33]: This works on Windows and Linux from GUI. The dcm2nii call we had till now is without using getApplicationPath("dcm2nii") and all the path magic was happening in this file. Was dcm2nii call really working on macOS earlier?  If it was working earlier, it should work even now. We will need to test on macOS and I am not sure how to test the GUI there.

Comment (sarthakpati) [reply src/view/gui/fDCM2NIfTI.cpp:33]: > This works on Windows and Linux from GUI

I am not disputing this. What I said was that it won't work on macOS. This is because the binaries are not in `QApplication::applicationDirPath()` for the macOS package (it is in `../Resources/bin/`). All other "packaged" external binaries are called using `getApplicationPath` to take care of this.

Comment (sarthakpati) [reply src/view/gui/fDCM2NIfTI.cpp:33]: As long as this is taken care of, these changes are great.

Comment (ashishsingh18) [reply src/view/gui/fDCM2NIfTI.cpp:33]: > 
> 
> > This works on Windows and Linux from GUI
> 
> I am not disputing this. What I said was that it won't work on macOS (BTW, the mechanism on the current master wouldn't work, either). This is because the binaries are not in `QApplication::applicationDirPath()` for the macOS package (it is in `../Resources/bin/`). All other "packaged" external binaries are called using `getApplicationPath` to take care of this.

The existing code may have never worked on macOS then.

Comment (ashishsingh18) [reply src/view/gui/fDCM2NIfTI.cpp]: @sarthakpati please check the modified file.

**Comment by ashishsingh18** [comment]
Can we test the artifacts on different platforms?
https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2165&view=artifacts&type=publishedArtifacts

@saimarathore could you test this on macOS?

The data to test with is on the cluster at: 
`"/cbica/home/sakoc/comp_space/lab/captk/180b/d2n"`

**Comment by ashishsingh18** [comment]
This is working on Windows and Linux. Perhaps, we should merge this.
In case there are issues with macOS, we can open an issue on github and fix.

File: src/applications/Utilities/src/Utilities.cxx [hunk 2]
```diff
@@ -405,49 +405,71 @@ int algorithmsRunner()
...
+	dicomFolderPath = cbica::getFilenamePath(inputImageFile);
+
+	// construct path to dcm2niix for debug/release modes and different OS
+	std::string m_exe; 
+#ifdef CAPTK_PACKAGE_PROJECT
+	#if WIN32
+		m_exe = cbica::getExecutablePath() + "/dcm2niix.exe";
+	#else
+		m_exe = cbica::getExecutablePath() + "/dcm2niix";
+	#endif
```
Comment (sarthakpati) [inline src/applications/Utilities/src/Utilities.cxx:418]: To add here:
```cpp
#ifndef __APPLE__
    m_exe = cbica::getExecutablePath() + "/dcm2niix";
#else
    m_exe = cbica::getExecutablePath() + "../Resources/bin/dcm2niix"
#endif
```

Comment (ashishsingh18) [reply src/applications/Utilities/src/Utilities.cxx:418]: Initially I was also thinking that we would need that check, but since the Utilities and dcm2niix are both in the same directory, it works. We don't need the `if __APPLE__` check.

Comment (sarthakpati) [reply src/applications/Utilities/src/Utilities.cxx:418]: Oh okay!
