### PR TITLE
Confetti change misc fixes

### LINKED ISSUE #763: Current Slice invalid value is still displayed
## Steps to Reproduce the Problem

  1. Enter an invalid (out-of-range) value in the X, Y, or Z field of `Current Slice`.

  1. Press `Update`.

  1. View does not change (as coordinate was invalid). But invalid value stays in the field where you entered it.

## Specifications

  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

### LINKED ISSUE #1050: Linux installer: re-word instructions
After running the Linux installer, there is an message about how to run CaPTk. Please change:

<To run CaPTk, locate to where CaPTk is installed and enter the command>

To:

<To run CaPTk, change to the directory where CaPTk is installed and enter the command>

### PR DESCRIPTION
**Pull request by AlexanderGetka-cbica**
Fixes #763 
Causes position selection to be bounded to the extent of the image -- attempted selections outside these bounds are instead changed to the closest index. This adds a minor check to Slicer.cpp causing this bounding and removes the related check from SlicerManager.
Fixes #1050
(changes message in linux-makeself) 

Contains minor changes to ConfettiCore.py enabling Confetti to be frozen/built into an executable with Nuitka, a python compiler that still supports 2.7.

I changed the ApplicationConfetti slot to just request "confetti" in the same style as the other apps -- the getApplicationPath function in CaPTkGUIUtils already looks for ConfettiGUI if you pass it "confetti". This also enables calling confetti to work in developer mode, at least on Windows. 

This contains a small set of fixes like actually instantiating fHelpTutorial -- previously it was an uninitialized object. Also differentiating the error message between Usage and About.

This also makes confetti run from the packaged executable on Linux for me ( see issue #865 )... but this needs to be tested further. We should check this in alpha.

### CODE REVIEW

File: src/view/gui/fMainWindow.h [hunk 1]
```diff
@@ -1563,7 +1563,7 @@ public slots:
   Fetalbrain mfetalbrain;
 
   fHelpDialog* mHelpDlg;
-  fHelpTutorial mHelpTutorial;
+  fHelpTutorial* mHelpTutorial;
```
Comment (sarthakpati) [inline src/view/gui/fMainWindow.h:1566]: Does this not need to get destroyed?

Comment (AlexanderGetka-cbica) [reply src/view/gui/fMainWindow.h:1566]: Good catch, normally I would parent these. But they act really really strangely when I do so.
Since they only really live until the application closes, and no others are created, this doesn't cause a leak in any practical sense.
Still, I just added a change that calls for its destruction in the destructor of fMainWindow.
