### PR TITLE
fix #860

### LINKED ISSUE #860: Preprocessing CLI (and maybe all CLIs) can't handle spaces in the filepaths
**Describe the bug**
```bash
###
### Escaping space doesn't work
###
dimitris@dimitris-lab:~/Documents/Programs/CaPTk-1.7.6-stable/CaPTk/1.7.6$ ./captk Preprocessing -i /home/dimitris/Documents/Medical\ Datasets/brain_tumor_5m/flair_5m.nii.gz -o /home/dimitris/Desktop/outdelll.nii.gz -zn
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /home/vsts/work/1/s/bin/ITK-source/Modules/Remote/MGHIO/src/itkMGHImageIO.cxx:160:
itk::ERROR: MGHImageIO(0x1f4d7f0): A FileName must be specified.
Aborted (core dumped)
### 
### Quotation marks around the path with the space doesn't work
###
dimitris@dimitris-lab:~/Documents/Programs/CaPTk-1.7.6-stable/CaPTk/1.7.6$ ./captk Preprocessing -i "/home/dimitris/Documents/Medical Datasets/brain_tumor_5m/flair_5m.nii.gz" -o /home/dimitris/Desktop/outdelll.nii.gz -zn
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /home/vsts/work/1/s/bin/ITK-source/Modules/Remote/MGHIO/src/itkMGHImageIO.cxx:160:
itk::ERROR: MGHImageIO(0x1ce77f0): A FileName must be specified.
Aborted (core dumped)
###
### Moving the image to a path without spaces works!
###
dimitris@dimitris-lab:~/Documents/Programs/CaPTk-1.7.6-stable/CaPTk/1.7.6$ ./captk Preprocessing -i /home/dimitris/Desktop/flair_5m.nii.gz -o /home/dimitris/Desktop/outdelll.nii.gz -zn
Cut-offs calculated: Lower = -26.8689; Upper = 379.75
dimitris@dimitris-lab:~/Documents/Programs/CaPTk-1.7.6-stable/CaPTk/1.7.6$
```

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Additional context**
- Also tried it for n3 and ss and can confirm that the issue is there for everything.
- This might be an issue on other CLIs too?
- Other seemingly different issues might be related to this, like #854 #858 (marked as critical because of this)

### PR DESCRIPTION
**Pull request by AlexanderGetka-cbica**
Fixes issue #860.
A change is made to how arguments are passed to the CWL applications when called through CaPTk from the command line. This should allow paths with spaces to be parsed correctly so long as the user indicates they are such (by surrounding them with quotes or by escaping the spaces in the path).

**Please test this on Windows and Mac, as they may handle system command line calls differently than Linux.**

### CODE REVIEW

File: src/CaPTk.cxx [hunk 1]
```diff
@@ -109,12 +109,12 @@ int main(int argc, char** argv)
         std::string argv_complete;
         for (size_t i = 2; i < argc; i++) // 2 because the argv[1] is always the "application"
         {
-          argv_complete += " " + std::string(argv[i]);
+          argv_complete += " \"" + std::string(argv[i]) + "\""; // add double quote for command tokenization
```
Comment (sarthakpati) [inline src/CaPTk.cxx]: This is probably not going to be enough. The issue is coming from ```CmdParser``` not being able to handle spaces. As a starting point, check this location, where the entire ```argv``` is populated: https://github.com/CBICA/CaPTk/blob/master/src/cbica_toolkit/src/cbicaCmdParser.cpp#L474

Comment (sarthakpati) [reply src/CaPTk.cxx]: My bad, I thought the issue was somewhere else.

**Comment by dboun** [comment]
(This has been tested on linux by alex so ignore azure failing for xenial. But someone should try it on windows because the tokenization might behave differently there)
